### ISSUE TITLE
Facebook button always loading

### ISSUE THREAD

**Issue by eaponiente** [adi518/vue-facebook-login-component#10]
Hello, I encountered an issue where the facebook login button is always loading like in the link [IMAGE](http://prntscr.com/ojarsj)

`<v-facebook-login
                app-id="12345678934567"
        ></v-facebook-login>`

It did displayed correctly once, but when I refreshed the page it returned to loading state. any ideas how is this happening?

**Comment by adi518** [comment]
Share more details, like a code snippet.

**Comment by eaponiente** [comment]
hello. I think its okay, the issue has been fixed I'm not sure why and how. I will try to observe if the issue will return, nevertheless the plugin is working great.
