### ISSUE TITLE
API calls from the server require an appsecret_proof argument

### ISSUE THREAD

**Issue by kapilpundit** [adi518/vue-facebook-login-component#11]
Hi @adi518 

Thanks for developing this nice component.

However I am facing a problem logging the users in. When I tried your component on my local environment, it seemed to work fine with my demo facebook app.

But, when I tried the code on a real server with https, I receive the following message from Facebook:

"API calls from the server require an appsecret_proof argument"

I found out that this document is the answer to resolving this problem.
[https://developers.facebook.com/docs/graph-api/securing-requests](https://developers.facebook.com/docs/graph-api/securing-requests)

 However I could not find how I can use it through your component.

Help would be appreciated.

Thanks,

**Comment by adi518** [comment]
There's a `loginOptions` prop that might help you with that.

**Comment by adi518** [comment]
Reopen if still relevant.
