### ISSUE TITLE
error Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by astanecki** [adi518/vue-facebook-login-component#12]
Hello,

Thanks for great component :racehorse: I see some opportunity to make it more useful

**Plugin version** 
1.3.6 

**Environment:**
Ubuntu 18.04.2 LTS Bionic

**Current behavior:**
When used in the project where babel-polyfill is also using, throws an error while running built app. 
```console
error Error: only one instance of babel-polyfill is allowed
```
It looks like the same problem as currently in number of other libs. Errors happen after importing component inside our app's vue file. 

**Expected behavior:**
Installing and importing component desn't throw error and app runs without console errors. 

Fixing it will help in using this helpful stuff, thanks :)

**Comment by adi518** [comment]
Hi, yea, looks like I'll have to remove `babel-polyfill` and have it added by consumers, thanks. 👍

**Comment by adi518** [comment]
Should be fixed with `1.3.7`. Moved babel-polyfill to consumer responsibility.

**Comment by astanecki** [comment]
Thank you, that's next step to make you package better :v: Let me know, aren't you afraid moving ``babel-polyfill`` to consumer is more risky in case using the newest es* features even on chrome / android or ios browsers?

**Comment by adi518** [comment]
Hmm, not sure I understand. Babel-polyfill is meant to cover new features for old browsers, like IE. If you target new browsers only, you definitely _don't_ need the polyfill overhead.
