### ISSUE TITLE
"Please wait..." indefinitely if FB is blocked

### ISSUE THREAD

**Issue by morebrackets** [adi518/vue-facebook-login-component#18]
If the user is using a tool to block the FB SDK (AdBlock/Ghostery/Facebook Container/Disconnect/Brave Shields/Etc.), the button just says "Please wait..." indefinitely. It would be nice to offer a slot for detecting this.

**Comment by adi518** [comment]
Thanks, I'll look into this. A PR is also welcome.

**Comment by adi518** [comment]
I believe this feature is now fulfilled with the release of `1.4.0` (see [docs](https://adi518.github.io/vue-facebook-login-component/#/)). This release also has introduces an important bugfix, which fixes SDK loading on subsequent component instance creations (this was especially evident in HMR).
