### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by retf** [adi518/vue-facebook-login-component#20]
I am getting this error, any idea?

Uncaught ReferenceError: regeneratorRuntime is not defined

code
<script>
import VFacebookLogin from 'vue-facebook-login-component'
export default {
  name: 'hello',
  components: {
    VFacebookLogin
  },
  data () {
    return {
      msg: 'Welcome to Your Vue.js PWA'
    }
  }
}
</script>

**Comment by adi518** [comment]
See #17. Search around next time. :)
