### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by jetstudio** [adi518/vue-facebook-login-component#22]
Can you please add the [sample's link](https://adi518.github.io/vue-facebook-login-component/#/) into the documentation as well as a [link](https://github.com/adi518/vue-facebook-login-component/blob/master/docs/src/views/Docs.vue) to the sample code? I believe it will be time saving for many others! Btw, thanks for the great work!

**Comment by adi518** [comment]
There's a link in the description of this repository.
