### ISSUE TITLE
Is it possible to use it on Nuxt ?

### ISSUE THREAD

**Issue by renztoygwapo** [adi518/vue-facebook-login-component#23]
I tried this install in nuxt application but I got an error, not able to use this one.

![image](https://user-images.githubusercontent.com/4898681/70763315-a04a3200-1d8e-11ea-93e0-3abab39b2a18.png)

P.S. It only works on Client Side Rendering but Didn't work on Server Side.

**Comment by adi518** [comment]
See #5.

**Comment by renztoygwapo** [comment]
Why is it closed ?
can we use in SSR ?
Thanks

**Comment by adi518** [comment]
Just read the comments and search next time.
