### ISSUE TITLE
Sign Out Not Working

### ISSUE THREAD

**Issue by Gyurmatag** [adi518/vue-facebook-login-component#24]
Hi!

I browsed through the issues and find out that someone had a similiar problem, like me now:
https://github.com/adi518/vue-facebook-login-component/issues/9

If I sign out and reload the browser window the previously signed in user is still logged in again. I've already set up my localhost url and app domain in the Facebook development platfrom, so I have no idea what is wrong with it.

Can you please help me?

**Comment by adi518** [comment]
Did you try the solution in #9?

**Comment by Gyurmatag** [comment]
Yes I tried it, already done that, but not working. :(

**Comment by adi518** [comment]
It works perfectly in my demo site, so it's probably an issue with your Facebook setup. If you resolve it, comment here to let others know.
