### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by aner87** [adi518/vue-facebook-login-component#25]
Hello, 
I have a perfectly working (and pretty simple) Vue project, in which I'd like to use this fb-login-component.
The moment I install it and load the component to implement it, the entire app stops loading and my browser's console displays this:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

I've been researching quite a bit, but I am unable to find a working solution to it. 
Is it related to babel deprecation by any chance?

Thanks to everybody that could help me :)

**Comment by adi518** [comment]
Search the issues.
