### ISSUE TITLE
FB.init options not applied.

### ISSUE THREAD

**Issue by susameca** [adi518/vue-facebook-login-component#28]
Hi, i have an issue with the component that if i click to logout on refresh is saying again logout. I tried to use the `status: false` option from https://developers.facebook.com/docs/javascript/reference/FB.init/v6.0 but with no success. Can this be achieved?

code:

<v-facebook-login app-id="******" :options="fbOptions" @connect="afterLogin" @login="tryLogin"></v-facebook-login>

data () {
	return {
		fbOptions: { status: false }
	}
}

**Comment by adi518** [comment]
I'm sorry, but this issue is really unorganized, I can't read it and I can't follow it. If it's an issue with Facebook API, then you'll have to figure it out from their docs.
