### ISSUE TITLE
Trigger logout by clicking button

### ISSUE THREAD

**Issue by guyver-dash** [adi518/vue-facebook-login-component#31]
Hi there,
Is there a way to trigger logout when the button is click... 

```
<button v-on:click="logout">Logout</button>
<v-facebook-login
            app-id="0000000000455"
            @sdk-init="handleSdkInit"
            @connect="handleConnect"
            @logout="handleLogout"
            @click="handleClick"
          >
          </v-facebook-login>
```
As you can see, I have a logout button and I need to logout also the facebook when the button logout is click. Thanks.

**Comment by adi518** [comment]
It should work out of the box. The demo source code only taps onto the logout event, but the trigger itself is already incorporated into the component. Re-investigate your issue.

**Comment by guyver-dash** [comment]
Thanks, I tried it and didn't work...  maybe `this.$refs.facebook.logout` would be great.
```
<v-facebook-login
           ref="facebook"
            app-id="0000000000455"
            @sdk-init="handleSdkInit"
            @connect="handleConnect"
            @logout="handleLogout"
            @click="handleClick"
          >
          </v-facebook-login>
```

**Comment by adi518** [comment]
I still fail to understand the problem. See the [demo](https://adi518.github.io/vue-facebook-login-component/#/). Click on it, then login, then click again (it will logout). Isn't that what you want?

**Comment by guyver-dash** [comment]
No that's not what I mean... I mean you have a `button` then it will trigger logout to your `<v-facebook-login>`

**Comment by adi518** [comment]
OK, so you want to attach the `logout` method to another button, other than the one rendered by the component, does that sound right?

**Comment by guyver-dash** [comment]
Yes... Thanks.

**Comment by adi518** [comment]
Looks like we can add `ref` to the scope component and that will make it available under `this.$refs.facebook.$refs.scope`. Seems a bit hacky, but worth a try. You can submit a PR or wait for a while until I get some spare time to add this feature.

**Comment by adi518** [comment]
OK, decided to have a quick go. It wasn't possible with `ref`, so I passed the `scope` object to the `sdk-init` event. Updated docs with example. 👍

**Comment by guyver-dash** [comment]
It works but there is an error... 
![aaa](https://user-images.githubusercontent.com/10149942/75086242-f1d02380-556c-11ea-87f2-e56489b65749.JPG)

**Comment by adi518** [comment]
Looks like you tried to attach it to a submit event, perhaps incorrectly. Try an arrow function: `@submit="() => facebook.scope.logout".

**Comment by guyver-dash** [comment]
`@click="facebook.scope.logout"` works but there is an error.  `@submit="() => facebook.scope.logout"`  is not working with the same error.

**Comment by adi518** [comment]
I just tried this and it works without any errors.
```html
<form v-if="facebook.scope.logout" @submit="facebook.scope.logout">
  <button>logout</button>
</form>
```
