### ISSUE TITLE
NuxtJS - Same Token in All Devices

### ISSUE THREAD

**Issue by BerkanSezer** [adi518/vue-facebook-login-component#32]
This is not working on NuxtJS. I had very big issue. 
When i logged in with facebook, i am getting access token and posting different request. When i open same site with the other devices. I already logged in first account. I don't understand anything :(

**Comment by adi518** [comment]
Can you provide a repro? I'm uncertain of the necessity to have this component support SSR. I'm going to need help to dig deeper into this.

**Comment by BerkanSezer** [comment]
I'll create a demo repo and i'll share with you. Thanks. I hope my code is bad because this library looks like perfect on VueJS :)

**Comment by BerkanSezer** [comment]
@adi518 I'm so sorry. This bug is about my badness. Vuex-store is caching the store when you assign as a object. I replaced to arrow function and thats all.  I'm sorry for your time.

**Comment by adi518** [comment]
No harm done. Reopen if relevant.
