### ISSUE TITLE
Slots not work

### ISSUE THREAD

**Issue by orhanmusellim** [adi518/vue-facebook-login-component#33]
i try use slots but not work.

`  <v-facebook-login app-id="------------" @sdk-init="initFacebookApi" @login="loginFacebook">`
`    <login>Facebook ile Giriş Yap</login>`
`    <logout>Facebook ile Çıkış Yap</logout>`
 ` </v-facebook-login>`

Please help me.

**Comment by mifff-lunglinh** [comment]
Hi, Do you have any solution?
