### ISSUE TITLE
There has no option to change facebook logo.

### ISSUE THREAD

**Issue by devghor** [adi518/vue-facebook-login-component#35]
Facebook has a recommendation to style login button. https://developers.facebook.com/docs/facebook-login/userexperience/#buttondesign
I want to change facebook logo icon.

**Comment by adi518** [comment]
I can add a slot to help you out with that. Hold short.

**Comment by adi518** [comment]
Relased new version: `1.6.0`, which includes two new features:
* Logo slot, for replacing the logo.
* `useAlternateLogo` prop for using an alternate logo.
