### ISSUE TITLE
autologin

### ISSUE THREAD

**Issue by gbkwiatt** [adi518/vue-facebook-login-component#37]
While I was thinking I got it to work ..
I switched to different PC with my project, where I have facebook logged in i browser. 

Now when I am going to login page in my project, it automatically triggers facebook login and doesn't even ask for accepting it, just logging it it. 
I am trying to log it out, then it works for a moment and after refreshing it does it again.
Is there a way to prevent that ? 
my options: 
```js
options: {
        cookie: false,
        autoLogAppEvents: false
      }
```

**Comment by adi518** [comment]
That's probably because the component calls `getLoginStatus` and that returns with `"connected"`, therefore you are still logged in. Did you try deleting your app data?

**Comment by adi518** [comment]
@gbkwiatt This issue will be closed if no feedback is received.
