### ISSUE TITLE
Login event provide "status" only instead of auth "response[Object]"

### ISSUE THREAD

**Issue by M1CK431** [adi518/vue-facebook-login-component#41]
From documentation (README.md):
![image](https://user-images.githubusercontent.com/31622263/80130487-f4fd8500-8598-11ea-8b97-c5f04b5d1ad7.png)

But we only have the status instead:
https://github.com/adi518/vue-facebook-login-component/blob/f42d8cfce96feea3b2c3e19952ce972533cb2066/packages/vue-facebook-login-component/src/components/Scope.js#L98

Can you please provide the whole auth response object instead of the status only?

**Comment by adi518** [comment]
Hi,

Thanks for pointing that out, it's a regression. Come around tomorrow for a fix.

**Comment by adi518** [comment]
See new release: `2.2.2`.

**Comment by desert** [comment]
Still present at line https://github.com/adi518/vue-facebook-login-component/blob/f42d8cfce96feea3b2c3e19952ce972533cb2066/packages/vue-facebook-login-component/src/components/Scope.js#L50

**Comment by M1CK431** [comment]
> Still present at line
> 
> https://github.com/adi518/vue-facebook-login-component/blob/f42d8cfce96feea3b2c3e19952ce972533cb2066/packages/vue-facebook-login-component/src/components/Scope.js#L50

In fact IMHO `login` event should even not be emited here at all. Personnaly I'm using this lake of parameter to make the difference between the initial state (the `login` event from L50) and the user login action (when the user click on the button).

**Comment by adi518** [comment]
But then, you cannot hook onto the initial login. It's possible you'll want to do something if the user is already logged in. You quite a lot of things you can use to create conditions for pretty much everything. If I remove or rename the event, it might break it for others.

**Comment by adi518** [comment]
We'll continue in #43.
