### ISSUE TITLE
Change SDK language

### ISSUE THREAD

**Issue by Guetso** [adi518/vue-facebook-login-component#51]
Hi ! Thank you for this, very helpful !

Is there any way to change the language of the SDK like ---> " src="https://connect.facebook.net/en_US/sdk.js " into src="https://connect.facebook.net/fr_FR/sdk.js ?

**Comment by adi518** [comment]
Hi, there's no such option atm, but I think I can add it rather quickly.

**Comment by Guetso** [comment]
I'll try to take the time for that this week (i have to tell, i'm a 'very' junior dev, i'v never did PR yet)

**Comment by adi518** [comment]
You should give it a go then.

**Comment by adi518** [comment]
Try new version: `2.4.0`.

**Comment by Guetso** [comment]
you didn't let me give a try :p, thks a lot tho
