### ISSUE TITLE
Don't switch the login button to the logout.

### ISSUE THREAD

**Issue by mifff-lunglinh** [adi518/vue-facebook-login-component#53]
Hi, I don't want to see the logut button after I login. Is there a way to not show the logout button after login?

**Comment by adi518** [comment]
You can use the login state to do a `v-if="loggedIn" on the button and that will hide it when the user is logged in.

**Comment by ivtod** [comment]
Hi @adi518,
it is not clear, can you please provide an example?
Thanks!
