### ISSUE TITLE
[Request] Support for NuxtJS

### ISSUE THREAD

**Issue by YoussF** [adi518/vue-facebook-login-component#58]
Hello,

First thank you for making this component. However, i tried to use it with NuxtJS and it seems to not work. I've seen that issue #5 is talking about that and i've tried the recommanded workaround (https://nuxtjs.org/api/components-no-ssr/) but even if a wrap the component with <client-only> it doesn't work. I don't know if i'm the only one to use Nuxt, but it would be very nice to have this component properly working on Nuxt. Can someone please check what's going one ? Thank a lot.

**Comment by gkkirilov** [comment]
Yeah I also tried registering it as a plugin but it throws `window is not defined`

**Comment by adi518** [comment]
I understand that NuxtJS support is an increasing necessity, so I'll try to get it done. PR is welcome and can quicken the process. 👍

**Comment by adi-works** [comment]
Ok, so I finally got to it and it seems all it required was going through the Nuxt docs. I got the component working without changing its code.

1. Setup Nuxt app with HTTPS:
	* Generate a self-signed certificate: https://stackoverflow.com/a/57895543/4106263
	* Configure `nuxt.config.js` for HTTPS: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-server#example-using-https-configuration

2. Import the component (client-side only):

```vue
<template>
  <client-only>
    <v-facebook-login app-id="966242223397117" />
  </client-only>
</template>

<script>
export default {
  components: {
    VFacebookLogin: () =>
      process.client ? import('vue-facebook-login-component') : null
  }
}
</script>
```

And that's it. I will add a note in the readme.

Edit: Done, see: https://adi518.github.io/vue-facebook-login/#/?a=nuxt-support

**Comment by adi518** [comment]
@YoussF @gkkirilov
