### ISSUE TITLE
How Can I Able to change the button text like 'Sign out with Facebook' and `Sign in with Facebook` with only `facebook`

### ISSUE THREAD

**Issue by saikiran-sankey** [adi518/vue-facebook-login-component#6]
@adi518 please help. Advance Thanks!!

**Comment by adi518** [comment]
You need to use slots. Please read the docs. 👍

**Comment by saikiran-sankey** [comment]
@adi518 is https is mandatory for Facebook integration in my website?

**Comment by adi518** [comment]
Afaik, these days it's mandatory.

**Comment by saikiran-sankey** [comment]
@adi518 Thank you!!

**Comment by saikiran-sankey** [comment]
![image](https://user-images.githubusercontent.com/39328377/58365184-0f893300-7ede-11e9-9bbb-ca10ae6a249a.png)
 @adi518  I'm doing like the above image shows. But still the values not get updated on my website.please help.

**Comment by adi518** [comment]
It should be:

```vue
<template v-slot="login">
  Facebook
</template>
```

You are not using slots correctly. Please read the [docs](https://vuejs.org/v2/guide/components-slots.html).

**Comment by vic-thedev** [comment]
what works fror me:
  <template >
      <v-facebook-login app-id="{ your app-id }"  v-slot:login>
        Facebook
      </v-facebook-login>
    </template>

**Comment by jcmanolong21** [comment]
@vic-thedev 
your answer returns an error
"Named slots muse use '<template>' on a custom element.

**Comment by jcmanolong21** [comment]
@adi518 I did the template v-slot but still gets the same texts on my button
![image](https://user-images.githubusercontent.com/44686119/98885953-f5765280-24cd-11eb-8143-401f180e99af.png)
![image](https://user-images.githubusercontent.com/44686119/98886002-12128a80-24ce-11eb-903c-5413d3cc9767.png)
I used the <template v-slot:login> instead of <template v-slot="login"> because it returns an error, see image below
![image](https://user-images.githubusercontent.com/44686119/98886070-3b331b00-24ce-11eb-97f9-b50bf4085e48.png)

**Comment by adi518** [comment]
Of course you are not going to see your content, you are logged in and "login" slot is only displayed when you are signed out.

**Comment by jcmanolong21** [comment]
Oh okay, so how do I exactly just disable the Sign out text? just Facebook or Continue to Facebook text. @adi518

**Comment by jcmanolong21** [comment]
I've already figured it out, and I also set the logout function as "login". but still, it does the logout function

**Comment by adi518** [comment]
Post a codepen or something, so I can understand better.

**Comment by jcmanolong21** [comment]
@adi518 here is the raw code
https://pastebin.com/EvjGJJme
here is the console of what I meant by setting the logout function to login

![image](https://user-images.githubusercontent.com/44686119/99602990-6c1acf00-2a3d-11eb-9e00-8e817506d520.png)
