### ISSUE TITLE
Facebook sdk logout when site reloads

### ISSUE THREAD

**Issue by zinken7** [adi518/vue-facebook-login-component#61]
Hi, thanks for great facebook login.
I have meet an issues that I can't fix myself.
After site reload FB auto logout.
I use component with CDN:
```
<v-facebook-login app-id="******" version="v8.0"
       v-model="model" @sdk-init="handleSdkInit" @login="handleLogin">
</v-facebook-login>
```
When I put FB.getLoginStatus in handleSdkInit():
```
handleSdkInit({ FB, scope }) {
      this.FB = FB;
      this.scope = scope;
      this.FB.getLoginStatus(function (response) {
        console.log(response);
      });
    },
```
It return "unknown" when reload site:
```
{authResponse: null, status: "unknown"}
  authResponse: null
  status: "unknown"
  __proto__: Object
```

**Comment by zinken7** [comment]
For more information, I use in Flask + Nginx + Gunicorn.
I Embed Directly your component in html.

**Comment by adi518** [comment]
You have to follow Facebook Login docs for this. It could be a server issue. The component is mostly a pass-through and doesn't take care of client/server integration.

**Comment by zinken7** [comment]
Thanks @adi518 for quick reply.
But everything work well on localhost(Flask)+ngrok https. Only when deploy to sever with Nginx and Gunicorn it's not working. Cookie disappeared after site reload.
It take me a fews day to fix but no result..

**Comment by zinken7** [comment]
And if I use [Button Login](https://developers.facebook.com/docs/facebook-login/web/login-button/) html with Facebook SDK JS it still working on sever. :(
Really dont know what is wrong here..

**Comment by zinken7** [comment]
Well, I do not do anything. I restart sever and it working now. 💯

**Comment by adi518** [comment]
I'd appreciate if you edit your comment to update it instead of creating new ones. There's really not much I can help with this. The component API logic is very generic, the rest depends on your integration.

**Comment by zinken7** [comment]
Thank you so much @adi518 . I will notice. I'm newbie with github. Have a great day!
