### ISSUE TITLE
multiple scope obj

### ISSUE THREAD

**Issue by MwSpaceLLC** [adi518/vue-facebook-login-component#8]
Sorry for this...

scope not work for me in this onj :(

**my button:**

< v-facebook-login :login-options="this.fb_obj" app-id="000000000000000"></v-facebook-login>

**my scope:**

        data() {
            return {
                params: {

                },

                fb_obj: {
                    scope: [
                        'publish_pages',
                        'manage_pages',
                        'pages_manage_instant_articles',
                        'read_page_mailboxes'
                    ]
                }
            }
        },

**Comment by MwSpaceLLC** [comment]
Ok sorry 😱😱😱.

i'm not a developer... i'm a stupid boy with code...... :(

![image](https://user-images.githubusercontent.com/29952045/60087803-01793d00-973e-11e9-94bc-0c3a5361a6d1.png)

Component work perfect!

**Comment by dannywillford** [comment]
@MwSpaceLLC what was your solution?  I'm having the same issue where for some reason the :login-options isn't being applied.
