### ISSUE TITLE
Vue-facebook-login : Not able to enable the button in case we abort signing in with Facebook.

### ISSUE THREAD

**Issue by YuvantBesre** [adi518/vue-facebook-login-component#83]
When we click on "Sign-in with Facebook" button, a loader turns off with the component getting disabled. However, in some cases, when we close the Facebook window, the loader still goes on and is disabled still. What to do in this case ? 

![image](https://user-images.githubusercontent.com/75745104/126828545-a049af87-9975-4f53-8275-e2596ae76cda.png)

**Comment by adi-works** [comment]
I'm not sure I understand. Can you post a gif or something? you can use the component state to do display logics. I'm not sure whether it's a bug or an advanced use-case.

**Comment by YuvantBesre** [comment]
Okay, below is the gif. However, let me explain you the issue in easy sentences : 
1. I click on "Continue with Facebook" from which the Facebook popup opens up asking for my Facebook credentials.
2. Now, for some reasons, I decided to close that popup without logging in by clicking the close window button on top-right. 
3. Upon clicking "Continue with Facebook" (as mentioned in 1.), the "Continue With Facebook" button is disabled with a loader on.
4. So, when I close the window as mentioned in step 2, the button is still disabled with the loader and I am forced to reload the page. 

How to solve this issue ?

**Comment by adi-works** [comment]
Now I understand, I'll check it.

**Comment by YuvantBesre** [comment]
> Now I understand, I'll check it.

Thank you. For security reasons, I am bound to remove the GIF. I will be waiting for your response as this is a blocker from my end. I really loved this package and I am using it. I just want this issue to go away so that my users face no issues.

**Comment by adi-works** [comment]
Which version do you use Vue 2 or 3?

**Comment by YuvantBesre** [comment]
> Which version do you use Vue 2 or 3?

I am using Vue 2.

**Comment by adi-works** [comment]
I'm unable to reproduce this issue, it's working fine. It goes back to normal state if I close the window. Make sure you have the latest version installed.

**Comment by YuvantBesre** [comment]
![image](https://user-images.githubusercontent.com/75745104/126960176-ad2bc823-abb7-4a0f-bad0-4957e6ad5554.png)
Still the same issue when I close the Facebook window without logging in, the loader is still spinning and the button is still disabled. 

I just uninstalled and installed your package once again. Still the same issue. Am I doing something wrong ? Can you specify the steps of doing this right ? Do I paste my code-base if you need it here ? I really need this issue fixed, your help would be appreciated.

**Comment by adi-works** [comment]
Try to use the component with the bare minimum. No custom styles and a single prop `app-id`. See if the issue persist and make sure to follow the docs again.

**Comment by YuvantBesre** [comment]
> Try to use the component with the bare minimum. No custom styles and a single prop `app-id`. See if the issue persist and make sure to follow the docs again.

**Comment by YuvantBesre** [comment]
> Try to use the component with the bare minimum. No custom styles and a single prop `app-id`. See if the issue persist and make sure to follow the docs again.

First of all, I am using nothing but the slots to use the my own custom button for that nothing else. Besides, I am sharing you my code base. Please have a look at them. May be you can catch an error.

**Comment by YuvantBesre** [comment]
``` abc ```

**Comment by YuvantBesre** [comment]
main.js : 

```js
import VFacebookLogin from 'vue-facebook-login-component'

Vue.component("login-with-facebook", VFacebookLogin)
```

The file in which I am using this component : 

```vue
<template>
  <login-with-facebook
    v-model="model"
    ref="fbcomponent"
    app-id="<my app id >"
    @sdk-init="handleSdkInit"
    @login="fillDataOnFacebookLogin"
    @click="fillDataOnFacebookLogin"
    class="social-media-btn facebook-btn"
  >
    <div class="mx-2" slot="login">Continue with Facebook</div>
    <img src="@/assets/homepage/facebook-logo.svg" slot="logo" alt="" />
  </login-with-facebook>
</template>

<script>
export default {
  data() {
    return {
      // FACEBOOK API DATA
      FB: {},
      scope: {},
      model: {},
    };
  },
  methods: {
    handleSdkInit({ FB, scope }) {
      this.FB = FB;
      this.scope = scope;
    },
    fillDataOnFacebookLogin() {
      this.FB.login((res) => {
        if (res.status === "connected") {
          this.FB.api(
            "/me?fields=id,first_name,name,email,picture.type(large)",
            (user) => {
              console.log(user);
              this.socialLoginData.loginType = 2;
              this.socialLoginData.userID = user.id;
              this.email = user.email;
              this.fullName = user.name;
              this.socialLoginData.firstName = user.first_name;
              this.socialLoginData.avatar = user.picture.data.url;
              this.googleSignupOrLogin();
            }
          );
        }
      });
    },
    logoutFromFacebook() {
      console.log(this.scope);
      this.scope.logout();
    },
  },
};
</script>
```

Above is my code. Please mention all the mistakes that is being done if there are any. I am basically following the steps from the docs.

**Comment by adi-works** [comment]
Please use [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) to format your code *before* you paste it here. This time I did it for you, but please take care of it next time. Also, paste in valid code, not broken, otherwise it makes things difficult.

I don't see anything obvious from this code, but please do what I suggested earlier, which is removing everything but the bare minimum required. Remove all props/slots/events from the component and pass only the required prop (`app-id`). Then, check if it works correctly or not.
