### ISSUE TITLE
Please provide a more detail explanation on how to use events in slot-scoped component

### ISSUE THREAD

**Issue by miratorimoonlight** [adi518/vue-facebook-login-component#84]
The documentation on component "VFBLoginScope" is too limited, and does not show how to add event handler like v-on:login in to the component.

**Comment by miratorimoonlight** [comment]
The documentation on component "VFBLoginScope" is too limited, and does not show how to add event handler like v-on:login in to the component.

**Comment by adi-works** [comment]
[This](https://adi518.github.io/vue-facebook-login/#/?a=events) table specifies the events, what's wrong with it?

**Comment by miratorimoonlight** [comment]
Could you provide an example of how to put those scope into the "VFBLoginScope"? [This](https://adi518.github.io/vue-facebook-login/#/?a=scope-component-example) shows nothing. For example, how do you put @login event in it?

**Comment by adi-works** [comment]
There's no need for such an example because it's basic Vue.js knowledge that you are expected to know beforehand. If you insist, there's this: https://github.com/adi518/vue-facebook-login/blob/master/packages/vue-facebook-login-component-docs/src/components/GetStarted.vue#L6.
