### ISSUE TITLE
How to show facebook icon always?

### ISSUE THREAD

**Issue by shizzic** [adi518/vue-facebook-login-component#87]
I mean and for static state and within working, and within logout, error, etc... ?
This is how i've removed text from the right sight of icon.
```
<template v-slot:login>{{ "" }}</template>
```
In another states icon doesn't show up at all.

**Comment by adi-works** [comment]
For that, you may have to compose your own button and use the underlying component to get the functionality. There's an example in the docs: https://adi518.github.io/vue-facebook-login/#/?a=scope-component-advanced-customization

**Comment by shizzic** [comment]
> For that, you may have to compose your own button and use the underlying component to get the functionality. There's an example in the docs: https://adi518.github.io/vue-facebook-login/#/?a=scope-component-advanced-customization

Thanks :)
