### ISSUE TITLE
How could i dynamic appId

### ISSUE THREAD

**Issue by mengxzh** [adi518/vue-facebook-login-component#88]
1. i have a input to accpt me input for appId
2. the appId will store with component data(){}
 3. when i login, the appId is not work for new appId

**Comment by adi-works** [comment]
This use case is a bit odd and not supported atm. If you know the app ids you will use ahead of time, you can create multiple components and just hide the ones that are not relevant. If you don't know the app ids ahead of time, I'll have to add support for such a case. You can also submit a PR.

**Comment by adi-works** [comment]
@mengxzh ?
