### ISSUE TITLE
Could not find a declaration file for module 'vue-facebook-login-component-next'

### ISSUE THREAD

**Issue by jimmiejackson414** [adi518/vue-facebook-login-component#91]
Are there typings available or this library? I'm receiving the error when attempting to import this library into my Vue3 project. I've tried adding `declare module 'vue-facebook-login-component-next';` to my d.ts file, however that still doesn't work.

**Comment by adi-works** [comment]
Hehe, no. At the time TS wasn't as prominent. I do want to move it to TS though, as I primarily use that now.

**Comment by jimmiejackson414** [comment]
I'm not too familiar with how the open-source project DefinitelyTyped works, but it might be worth supplementing this project with a contribution there because then you could avoid a rewrite here. Thanks for the response and great library!

**Comment by adi-works** [comment]
Glad you like it. DefinitelyTyped is a valid option, but I prefer to type and maintain just one source. It shouldn't be too difficult to move it to TS, I just need a spare weekend, hehe.
