### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-facebook-login-component'

### ISSUE THREAD

**Issue by ghost** [adi518/vue-facebook-login-component#93]
Hi I am getting this error;

`ERROR in ./src/views/FBLogin.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/FBLogin.vue?vue&type=script&setup=true&lang=js) 1:0-58`

**Comment by adi-works** [comment]
Please provide some context.
