### ISSUE TITLE
It doesn't work with Vue3

### ISSUE THREAD

**Issue by Dagge11** [adi518/vue-facebook-login-component#94]
There is no user data from the FB and it gives an error that says `The method FB.login can no longer be called from http pages` although Facebook allows http localhost testing

**Comment by adi-works** [comment]
Did you install the Vue 3 version of it?

**Comment by Dagge11** [comment]
Of course I did

**Comment by adi-works** [comment]
Sounds more like a configuration issue. That error message comes from Facebook's SDK, not the component.
